# Generated by Django 3.0.6 on 2020-05-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Feito', 'Feito'), ('Recebido', 'Recebido'), ('Iniciado', 'Iniciado'), ('Saiu para entrega', 'Saiu para entrega'), ('Entregue', 'Entregue')], default='Feito', max_length=50, verbose_name='Status')),
                ('dataHoraPedido', models.CharField(max_length=20, verbose_name='Data/Hora do pedido')),
                ('dataHoraEntrega', models.CharField(blank=True, max_length=20, verbose_name='Data/Hora da entrega')),
                ('formaPagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão')], max_length=50, verbose_name='Forma de pagamento')),
                ('ValorTotal', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor total')),
                ('Endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Endereco', to='dashboard.Endereco')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='dashboard.Usuario')),
                ('produtosPedidos', models.ManyToManyField(to='dashboard.ProdutoPedido')),
            ],
        ),
    ]
